Repository CA-G12/Serise-Fadi-Ali, pull requests merged in 2022-08, with the labels that each got.

#6 add node version to package.json
  package-lock.json
  package.json
Labels: await-review

#7 Readme file
  README.md
Labels: approved

#12 create the movie cart and styling
  public/app.css
  public/index.html
  public/pages/series/index.html
  public/pages/series/style.css
Labels: await-review

#11 Create search section in the landing pagr
  public/app.css
  public/assets/bg.png
  public/index.html
Labels: approved

#16 create file test
  test/test.test.js
Labels: await-review

#15 Add the tv shows object with an array of tv shows name
  src/seriesList.js
Labels: approved

#20 Install dotenv and created .env file
  .gitignore
  package.json
Labels: approved

#23 make dom movie cart
  public/pages/series/index.html
  public/pages/series/index.js
Labels: await-review

#25 22 serve index
  public/index.html
  src/routes.js
  src/server.js
  test/test.test.js
Labels: approved

#27 Get data from frontend and filter it
  public/app.js
  public/index.html
  public/js/app.js
  public/js/fetch.js
  src/routes.js
  src/seriesList.js
Labels: await-review

#29 Disply search suggestions in datalist tags
  public/index.html
  public/js/app.js
Labels: merged

#31 Handel series route
  package.json
  public/pages/series/index.html
  src/handel-move.js
  test/test.test.js
Labels: await-review

#34 33 code refactor
  package.json
  public/index.html
  public/js/app.js
  src/handel-move.js
  src/handlers/handlers.js
  src/handlers/home.js
  src/handlers/notFound.js
  src/handlers/response.js
  src/handlers/search.js
  src/handlers/series.js
  src/routes.js
  src/seriesList.js
Labels: approved

#35 create the button in the cart move page
  public/pages/series/index.html
  public/pages/series/style.css
Labels: await-review

#37 creat the btn in the dom
  public/pages/series/index.html
  public/pages/series/index.js
  public/pages/series/style.css
Labels: await-review

#38 Add genaric functions file with search and fs.read functions
  src/handlers/genaricResponse.js
  src/handlers/handlers.js
  src/handlers/home.js
  src/handlers/notFound.js
  src/handlers/response.js
  src/handlers/search.js
  src/handlers/series.js
Labels: approved

#41 Fix entry point path in package.json file
  package.json
Labels: approved, merged

#42 create image bar
  public/pages/series/index.html
  public/pages/series/index.js
  public/pages/series/style.css
Labels: await-review

#43 30 fetch series
  public/app.css
  public/index.html
  public/js/app.js
  public/pages/series/fetch.js
  public/pages/series/index.html
  public/pages/series/index.js
  public/pages/series/style.css
  src/handlers/checkSearch.js
  src/handlers/handlers.js
  src/routes.js
Labels: await-review
